# Generated by Django 3.2.3 on 2021-06-21 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellidos', models.CharField(max_length=25)),
                ('foto', models.FileField(unique=True, upload_to='')),
                ('nacimiento', models.DateField()),
            ],
            options={
                'db_table': 'actor',
                'ordering': ['apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Biografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
            options={
                'db_table': 'biografia',
                'ordering': ['texto'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('capital', models.CharField(blank=True, max_length=50, null=True)),
                ('continent', models.CharField(blank=True, max_length=50, null=True)),
                ('national_flag', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellidos', models.CharField(max_length=25)),
                ('foto', models.FileField(unique=True, upload_to='')),
                ('nacimiento', models.DateField()),
                ('biografia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cine.biografia')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.country')),
            ],
            options={
                'db_table': 'director',
                'ordering': ['apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('movie_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'favourites',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.TextField(blank=True, null=True)),
                ('ciudad', models.TextField(blank=True, null=True)),
                ('paraje', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lugares',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('president', models.CharField(blank=True, max_length=50, null=True)),
                ('foundation', models.IntegerField(blank=True, default=1900, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.country')),
            ],
            options={
                'db_table': 'studios',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('cost', models.IntegerField(blank=True, default=0, null=True)),
                ('income', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('actors', models.ManyToManyField(to='cine.Actor')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.country')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.director')),
                ('genres', models.ManyToManyField(to='cine.Genre')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cine.studio')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='biografia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cine.biografia'),
        ),
        migrations.AddField(
            model_name='actor',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.country'),
        ),
    ]
